=== KwonJaeMin/WHTM_EPM/MainProgram/Config/Config.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT Configs	(#PCDATA|LogConfig|DBConfig|UserConfig|SiteConfig|EtcConfig|SpecConfig|Logger)*>
<!ELEMENT LogConfig (#PCDATA)>
<!ELEMENT DBConfig (#PCDATA)>
<!ELEMENT UserConfig (#PCDATA)>
<!ELEMENT SiteConfig (#PCDATA)>
<!ELEMENT SiteScanFiles (ScanFile)*>
<!ELEMENT ScanFile (#PCDATA)>
<!ELEMENT ScanObjectConfig (ScanObject)*>
<!ELEMENT ScanObject (#PCDATA)>
<!ELEMENT Logger (LogInfoConfig)*>
<!ELEMENT LogInfoConfig (#PCDATA)>
<!ELEMENT SpecConfig (#PCDATA)>
<!ELEMENT EtcConfig (#PCDATA)>

<!ATTLIST LogConfig
  LogPath CDATA #REQUIRED
  LogUseDay CDATA #REQUIRED
  CPUQuantity CDATA #REQUIRED
>
<!ATTLIST DBConfig
  DBPath CDATA #REQUIRED
  DBLogPath CDATA #REQUIRED
  DBName CDATA #IMPLIED
  DBLogName CDATA #IMPLIED
>
<!ATTLIST UserConfig
  UserAccount CDATA #REQUIRED
  UserPassword CDATA #REQUIRED
>
<!ATTLIST SiteConfig
  SiteName CDATA #REQUIRED
  SystemMode (SimulationMode|FABMode) "SimulationMode"
>
<!ATTLIST LogInfoConfig
  LogID ID #REQUIRED
  LogKey CDATA #REQUIRED
  LogThreadName CDATA #IMPLIED
  LogName CDATA #REQUIRED
  FilePath CDATA #REQUIRED 	
  FileExt CDATA #REQUIRED	
  DeletePeriod CDATA #REQUIRED 	
  DeletePeriodDateTimeInterval (Year|Month|Day|Hour|Minute|Second) "Day"
  FileNamingRule (yyyy|yyyyMM|yyyyMMdd|yyyyMMddHH|yyyyMMddHHmm|yyyyMMddHHmmss) "yyyyMMdd"
  FolderNamingRule (yyyy|yyyy_MM|yyyy_MM_dd|yyyy_MM_dd_HH|yyyyMM|yyyyMM_dd|yyyyMM_dd_HH|yyyyMMdd|yyyyMMdd_HH) "yyyy_MM_dd"
  LogDelimiter CDATA #IMPLIED
  FreeSpace (5|10|15|20|25|30|35|40|45|50) "20"
>
<!ATTLIST SpecConfig
  O2 CDATA #REQUIRED
  H2O CDATA #REQUIRED
  Pressure CDATA #REQUIRED
  VSPCount CDATA #REQUIRED
  VSPTotalCount CDATA #REQUIRED
>

<!--CVD추가-->
<!ATTLIST EtcConfig
  Title CDATA #REQUIRED
  DispSiteName  CDATA #REQUIRED
  ProjectName CDATA #REQUIRED
  EqpID CDATA #REQUIRED
>

=== KwonJaeMin/WHTM_EPM/MainProgram/Config/Config.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Configs SYSTEM "Config.dtd">
<Configs>
  <!--여기에 이 이상의 내용을(Log제외) 넣지 마세요. this.GetCustomProperty. this.SetCustomProperty 를 사용 바랍니다.-->
  <LogConfig LogPath="C:\LOG\WHTM" LogUseDay="30" CPUQuantity="20" ></LogConfig>
  <UserConfig UserAccount="Adminstrator" UserPassword="1" ></UserConfig>
  <SiteConfig SiteName="WHTM" SystemMode="FABMode"></SiteConfig>
  <EtcConfig Title="WHTM-TEG CIM" DispSiteName="WHTM" ProjectName="TEG PROJECT" EqpID="A1TEG200"> </EtcConfig>
  <DBConfig DBPath="" DBLogPath="" DBName ="" DBLogName=""></DBConfig>
  <Logger>
    <LogInfoConfig LogID="LOG1" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="EXCEPTION" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMdd" FolderNamingRule="yyyyMM" FreeSpace="20"></LogInfoConfig>
    <LogInfoConfig LogID="LOG2" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="UI" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMdd" FolderNamingRule="yyyyMM" FreeSpace="20"></LogInfoConfig>
    <LogInfoConfig LogID="LOG3" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="SYSTEM" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMdd" FolderNamingRule="yyyyMM" FreeSpace="20"></LogInfoConfig>
    <LogInfoConfig LogID="LOG4" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="MELSEC" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMddHH" FolderNamingRule="yyyyMMdd" FreeSpace="20"></LogInfoConfig>
    <LogInfoConfig LogID="LOG5" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="DEBUG" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMdd" FolderNamingRule="yyyyMM" FreeSpace="20"></LogInfoConfig>
    <LogInfoConfig LogID="LOG6" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="MESSAGE" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMdd" FolderNamingRule="yyyyMM" FreeSpace="20"></LogInfoConfig>
    <LogInfoConfig LogID="LOG7" LogKey="SYSTEM" LogThreadName="SYSTEM" LogName="METERIAL_DATA" FilePath="[LogPath]" FileExt="log"  DeletePeriod="6" DeletePeriodDateTimeInterval="Month" FileNamingRule="yyyyMMdd" FolderNamingRule="yyyyMM" FreeSpace="20"></LogInfoConfig>
  </Logger>
</Configs>
